github: [Dev-moe-kyawaung]
patreon: # Your Patreon username
open_collective: # Your Open Collective username
ko_fi: # Your Ko-fi username
tidelift: # Your Tidelift name
custom: ['https://www.paypal.com/paypalme/my/profile']
